language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
services:
  - mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies
#before_install:
#  - "sudo apt-get update -qq"
#  - "sudo apt-get install -qq libldap2-dev libsasl2-dev"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install python-coveralls"
  - "python setup.py -q install"
#  - "echo data_file=$TRAVIS_BUILD_DIR/.coverage >> .coveragerc"
before_script:
  - sleep 10

# command to run tests
script:
   - nosetests
   - flake8 --ignore E501 biomaj_user/*.py
#after_success:
#  - coveralls

